/**
 * stepExpectationService.ts
 *
 * Generates a structured "pre-step preview" for the Autism Learning Library.
 * Before each lesson or assignment, the UI shows the user:
 *   - What will happen
 *   - How long it takes
 *   - What is expected of them
 *
 * These are generated by the LLM from the task metadata (title + content snippet).
 * Falls back gracefully to a static heuristic if the API is unavailable.
 */

import { callGemini } from './geminiService';

export interface StepExpectation {
  whatWillHappen: string;
  howLongItTakes: string;
  whatIsExpected: string;
}

function buildPrompt(type: 'lesson' | 'assignment', title: string, contentSnippet: string): string {
  return `You are an AI assistant helping a student with autism prepare for their next learning activity.
Generate a short, calm, clear, and friendly "preview card" for the following task.
Be very specific and concrete. Avoid vague language. Use simple sentence structures.

Task Type: ${type === 'lesson' ? 'Learning Lesson' : 'Assignment / Written Task'}
Task Title: "${title}"
Task Content Snippet: "${contentSnippet.slice(0, 300)}"

Respond with ONLY a raw JSON object (no markdown, no code fences) in this exact format:
{
  "whatWillHappen": "A 1-sentence description of what the student will do. e.g. 'You will watch a short video about Neurodiversity and then answer a few quiz questions.'",
  "howLongItTakes": "A brief time estimate, e.g. '5-10 minutes'",
  "whatIsExpected": "A 1-sentence statement of what the student needs to do to complete this step. e.g. 'Answer at least half the quiz questions correctly to mark this lesson done.'"
}`;
}

function getFallbackExpectation(type: 'lesson' | 'assignment', title: string): StepExpectation {
  if (type === 'lesson') {
    return {
      whatWillHappen: `You will study the lesson: "${title}". It may include a video or a short article to read.`,
      howLongItTakes: '5–15 minutes',
      whatIsExpected: 'Complete the material and click "Mark Lesson Complete" when you are done.',
    };
  }
  return {
    whatWillHappen: `You will review a teacher instruction for: "${title}" and use the AI Clarifier if any part is unclear.`,
    howLongItTakes: '10–20 minutes',
    whatIsExpected: 'Read the instruction, optionally break it down with AI, then click "Mark Assignment Complete".',
  };
}

export async function generateStepExpectation(
  type: 'lesson' | 'assignment',
  title: string,
  contentSnippet: string
): Promise<StepExpectation> {
  try {
    const prompt = buildPrompt(type, title, contentSnippet);
    const raw = await callGemini(prompt);

    if (!raw) return getFallbackExpectation(type, title);

    // Strip potential markdown code fences
    const cleaned = raw.replace(/```json|```/g, '').trim();
    const parsed: StepExpectation = JSON.parse(cleaned);

    if (parsed.whatWillHappen && parsed.howLongItTakes && parsed.whatIsExpected) {
      return parsed;
    }
  } catch (err) {
    console.warn('[StepExpectationService] Falling back to heuristic:', err);
  }

  return getFallbackExpectation(type, title);
}
