/**
 * StepExpectation.tsx
 *
 * Renders a calming "What to expect" preview card before each lesson or assignment
 * in the Autism Learning Library. Helps reduce uncertainty-triggered anxiety
 * by explicitly setting expectations before the student begins any task.
 *
 * Data is generated by the LLM via stepExpectationService.ts.
 * Falls back to a heuristic if the API is unavailable.
 */

import React, { useState, useEffect } from 'react';
import {
  generateStepExpectation,
  type StepExpectation,
} from '../../services/stepExpectationService';

interface StepExpectationProps {
  type: 'lesson' | 'assignment';
  title: string;
  contentSnippet: string;
  onBegin: () => void;
}

const StepExpectationCard: React.FC<StepExpectationProps> = ({
  type,
  title,
  contentSnippet,
  onBegin,
}) => {
  const [expectation, setExpectation] = useState<StepExpectation | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setExpectation(null);

    generateStepExpectation(type, title, contentSnippet).then((result) => {
      if (!cancelled) {
        setExpectation(result);
        setLoading(false);
      }
    });

    return () => { cancelled = true; };
  }, [type, title, contentSnippet]);

  const typeLabel = type === 'lesson' ? '📖 Lesson Preview' : '✏️ Assignment Preview';
  const typeColor = type === 'lesson' ? '#2b6cb0' : '#744210';
  const typeBg = type === 'lesson' ? '#ebf8ff' : '#fefcbf';
  const typeBorder = type === 'lesson' ? '#90cdf4' : '#f6e05e';

  return (
    <div style={{
      backgroundColor: typeBg,
      border: `2px solid ${typeBorder}`,
      borderRadius: '1rem',
      padding: '2rem',
      marginBottom: '1.5rem',
      fontFamily: "'Inter', system-ui, sans-serif",
    }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '1.25rem' }}>
        <span style={{
          backgroundColor: typeColor,
          color: '#fff',
          padding: '0.3rem 0.85rem',
          borderRadius: '2rem',
          fontSize: '0.8rem',
          fontWeight: 700,
          textTransform: 'uppercase',
          letterSpacing: '0.05em',
        }}>
          {typeLabel}
        </span>
        <span style={{ fontSize: '1.05rem', fontWeight: 700, color: '#1a202c' }}>{title}</span>
      </div>

      {loading ? (
        <div style={{ color: '#4a5568', fontStyle: 'italic', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          <span style={{ fontSize: '1.25rem', animation: 'spin 1s linear infinite' }}>⏳</span>
          <span>Preparing your step overview...</span>
        </div>
      ) : expectation ? (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.85rem' }}>
          <Row icon="🔍" label="What will happen" value={expectation.whatWillHappen} />
          <Row icon="⏱️" label="How long it takes" value={expectation.howLongItTakes} />
          <Row icon="✅" label="What is expected" value={expectation.whatIsExpected} />
        </div>
      ) : null}

      <button
        onClick={onBegin}
        disabled={loading}
        style={{
          marginTop: '1.75rem',
          padding: '0.85rem 2rem',
          backgroundColor: loading ? '#a0aec0' : typeColor,
          color: '#fff',
          border: 'none',
          borderRadius: '0.5rem',
          fontWeight: 700,
          fontSize: '1rem',
          cursor: loading ? 'not-allowed' : 'pointer',
          transition: 'background-color 0.2s',
          width: '100%',
        }}
      >
        {loading ? 'Please wait…' : `I'm ready — Begin ${type === 'lesson' ? 'Lesson' : 'Assignment'} →`}
      </button>
    </div>
  );
};

const Row: React.FC<{ icon: string; label: string; value: string }> = ({ icon, label, value }) => (
  <div style={{
    backgroundColor: 'rgba(255,255,255,0.7)',
    borderRadius: '0.5rem',
    padding: '0.85rem 1rem',
    display: 'flex',
    gap: '0.75rem',
    alignItems: 'flex-start',
  }}>
    <span style={{ fontSize: '1.25rem', flexShrink: 0 }}>{icon}</span>
    <div>
      <div style={{ fontSize: '0.75rem', fontWeight: 700, color: '#718096', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: '0.2rem' }}>{label}</div>
      <div style={{ fontSize: '0.95rem', color: '#2d3748', lineHeight: 1.5 }}>{value}</div>
    </div>
  </div>
);

export default StepExpectationCard;
