/**
 * disabilitySymptoms.ts
 * 
 * Centralized registry of keyword symptoms and markers for different disability profiles.
 * Used for AI auto-classification, string matching, and as a reference prompt for LLMs.
 * 
 * Each array targets ~500 entries covering clinical terms, casual speech,
 * apostrophe-free variants, and multi-word phrases people commonly use.
 */

export const visualWords = [
  // ── Clinical / Medical ──────────────────────────────────────────────────
  'blind', 'blindness', 'visual', 'vision', 'eye', 'eyes', 'sight', 'eyesight',
  'screen reader', 'low vision', 'partially sighted', 'visually impaired',
  'retina', 'retinal', 'glaucoma', 'cataract', 'cataracts', 'macular',
  'macular degeneration', 'optic', 'optic nerve', 'cornea', 'corneal',
  'lens implant', 'eye surgery', 'eye condition', 'eye disease', 'eye disorder',
  'nystagmus', 'strabismus', 'amblyopia', 'lazy eye', 'detached retina',
  'diabetic retinopathy', 'retinitis pigmentosa', 'keratoconus', 'astigmatism',
  'presbyopia', 'myopia', 'hyperopia', 'diplopia', 'double vision',
  'scotoma', 'hemianopia', 'cortical visual impairment', 'cvi',
  'legal blindness', 'legally blind', 'total blindness', 'night blindness',
  'color blind', 'colour blind', 'colorblind', 'colourblind', 'color deficient',
  'achromatopsia', 'tritanopia', 'deuteranopia', 'protanopia',
  'photophobia', 'light sensitive', 'light sensitivity',

  // ── Assistive Tech / Tools ──────────────────────────────────────────────
  'braille', 'braille display', 'refreshable braille', 'cane', 'white cane',
  'guide dog', 'seeing eye dog', 'magnifier', 'magnification', 'magnifying',
  'zoom', 'screen magnifier', 'zoomtext', 'magnification software',
  'contrast', 'high contrast', 'inverted colors', 'inverted colours',
  'dark mode', 'dark theme', 'tts', 'text to speech', 'speech output',
  'voiceover', 'jaws', 'nvda', 'narrator', 'talkback', 'orca',
  'screen curtain', 'audio description', 'descriptive audio',
  'optical character recognition', 'ocr', 'text recognition',
  'voice assistant', 'siri', 'alexa accessibility',

  // ── Casual / Conversational ─────────────────────────────────────────────
  "can't see", 'cant see', 'cannot see', 'hard to see', 'trouble seeing',
  'difficulty seeing', 'struggling to see', 'barely see', 'can barely see',
  'see very little', 'see nothing', 'see almost nothing',
  'everything is dark', 'everything looks dark', 'world is dark',
  'blurry', 'blur', 'blurred', 'fuzzy', 'hazy', 'foggy vision',
  'cloudy vision', 'cloudy eyes', 'things look cloudy',
  'losing my sight', 'lost my sight', 'going blind', 'becoming blind',
  'born blind', 'always been blind', 'never could see',
  'squint', 'squinting', 'strain my eyes', 'eye strain', 'eyes hurt',
  'eyes tired', 'eyes fatigue', 'sore eyes', 'burning eyes',
  'screen too bright', 'too bright', 'bright hurts', 'light hurts',
  'font too small', 'text too small', 'print too small', 'letters too small',
  'need bigger text', 'need larger font', 'enlarge', 'enlarge text',
  'need glasses', 'wearing glasses', 'thick glasses', 'strong prescription',
  'contact lens', 'contact lenses', 'contacts', 'eye patch',
  'bad eyesight', 'poor eyesight', 'weak eyesight', 'failing eyesight',
  'poor vision', 'weak vision', 'limited vision', 'reduced vision',
  'peripheral vision', 'tunnel vision', 'no peripheral',
  'depth perception', 'no depth perception',
  'eye problem', 'eye problems', 'eye issues', 'eye trouble',
  'seeing things', 'distorted vision', 'wavy lines', 'floaters',
  'flashes of light', 'spots in vision', 'black spots',

  // ── Multi-word phrases ──────────────────────────────────────────────────
  'near sighted', 'nearsighted', 'short sighted', 'shortsighted',
  'far sighted', 'farsighted', 'long sighted', 'longsighted',
  'blurry vision', 'blurred vision', 'losing sight', 'lost sight',
  'see far', 'see far away', 'see up close', 'see close up',
  'see the board', 'see the screen', 'see my phone', 'see my computer',
  'read the text', 'read small print', 'read without glasses',
  'face recognition', 'recognize faces', 'identify people',
  'night vision', 'see at night', 'see in the dark',
  'distance vision', 'close up vision', 'reading vision',
  'visual field', 'field of vision', 'side vision',
  'eye drops', 'eye medication', 'eye doctor', 'ophthalmologist',
  'optometrist', 'optician', 'eye specialist', 'eye exam',
  'visual acuity', 'snellen chart', '20/20', 'visual impairment',
  'sight loss', 'vision loss', 'progressive vision loss',
  'congenital blindness', 'acquired blindness', 'sudden vision loss',

  // ── Emotional / Impact ──────────────────────────────────────────────────
  'afraid of going blind', 'scared of losing sight', 'vision getting worse',
  'eyes getting worse', 'sight deteriorating', 'vision deteriorating',
  'independent despite vision', 'navigate without sight',
  'bumping into things', 'tripping over', 'falling because cant see',
  'miss things', 'miss details', 'overlook things',
  'hard to read signs', 'hard to see faces', 'hard to drive',
  'gave up driving', 'stopped driving', 'dangerous to drive',
];

export const adhdWords = [
  // ── Clinical / Medical ──────────────────────────────────────────────────
  'adhd', 'add', 'attention deficit', 'attention deficit disorder',
  'attention deficit hyperactivity', 'hyperactivity disorder',
  'inattentive type', 'hyperactive type', 'combined type',
  'executive function', 'executive dysfunction', 'executive functioning',
  'working memory', 'short attention', 'attention span',
  'neurodevelopmental', 'dopamine', 'norepinephrine',
  'reward system', 'reward deficiency',

  // ── Medication ──────────────────────────────────────────────────────────
  'medication', 'ritalin', 'adderall', 'concerta', 'vyvanse',
  'strattera', 'methylphenidate', 'amphetamine', 'dexedrine',
  'focalin', 'daytrana', 'intuniv', 'kapvay', 'stimulant',
  'non stimulant', 'medicated', 'unmedicated', 'off meds', 'on meds',

  // ── Core symptoms ───────────────────────────────────────────────────────
  'distract', 'distracted', 'distractible', 'distraction', 'distractions',
  'attention', 'inattention', 'inattentive', 'paying attention',
  'concentrate', 'concentration', 'concentrating',
  'focus', 'focused', 'focusing', 'unfocused', 'lack of focus',
  'hyperactiv', 'hyperactive', 'hyper', 'restless', 'restlessness',
  'impulsiv', 'impulsive', 'impulsivity', 'impulse', 'impulse control',
  'fidget', 'fidgeting', 'fidgety', 'squirm', 'squirming',
  'sit still', 'sitting still', 'stay still', 'stay seated',

  // ── Casual / Conversational ─────────────────────────────────────────────
  "can't focus", 'cant focus', 'cannot focus',
  'hard to focus', 'trouble focusing', 'difficulty focusing',
  'struggling to focus', 'lose focus', 'losing focus', 'lost focus',
  "can't concentrate", 'cant concentrate', 'cannot concentrate',
  'hard to concentrate', 'trouble concentrating',
  "can't pay attention", 'cant pay attention', 'cannot pay attention',
  'mind wander', 'mind wanders', 'wandering mind', 'mind drifts',
  'zoning out', 'zone out', 'zoned out', 'spacing out', 'spaced out',
  'daydream', 'daydreaming', 'staring into space', 'blank stare',
  "can't sit", 'cant sit', 'cannot sit', "can't sit still", 'cant sit still',
  'always moving', 'need to move', 'bounce around', 'bouncing around',
  'forgetful', 'forget things', 'keep forgetting', 'always forgetting',
  'forgot again', 'memory issues', 'bad memory', 'poor memory',
  'lose things', 'losing things', 'misplace', 'misplacing',
  'lost my keys', 'lost my phone', 'where did i put',
  'procrastinat', 'procrastinate', 'procrastinating', 'procrastination',
  'putting off', 'put things off', 'put it off', 'last minute',
  'leave everything', 'wait until last', 'deadline',
  'time management', 'manage time', 'managing time', 'bad with time',
  'losing track', 'track of time', 'lose track of time', 'time blind',
  'time blindness', 'no sense of time', 'always late', 'running late',
  'easily bored', 'get bored', 'bored easily', 'boring',
  'need stimulation', 'need excitement', 'crave novelty',
  'too many tabs', 'overwhelmed by tasks', 'task switching', 'multitask',
  'multitasking', 'switch tasks', 'jumping between', 'bouncing between',
  'scattered', 'scatterbrained', 'all over the place',
  'disorganiz', 'disorganis', 'disorganized', 'disorganised',
  'messy', 'chaotic', 'cluttered', 'piles of stuff',
  'cant finish', 'cannot finish', 'never finish', 'start but not finish',
  'start things', 'abandon projects', 'give up halfway',
  'interrupt', 'interrupting', 'blurt out', 'blurting',
  'impatient', "can't wait", 'cant wait', 'cannot wait', 'hate waiting',
  'act without thinking', 'regret saying', 'said without thinking',

  // ── Hyperfocus ──────────────────────────────────────────────────────────
  'hyperfocus', 'hyper focus', 'over focus', 'fixat', 'fixate', 'fixated',
  'obsessed with one thing', 'lost in activity', 'hours disappeared',
  'forgot to eat', 'forgot to sleep', 'tunnel vision on task',
  'intense focus', 'deep focus', 'in the zone', 'flow state',

  // ── Emotional / Impact ──────────────────────────────────────────────────
  'emotional dysregulation', 'mood swings', 'rejection sensitive',
  'rejection sensitivity', 'rsd', 'easily frustrated', 'quick temper',
  'overwhelmed', 'overwhelm', 'burnout', 'adhd burnout',
  'exhausted', 'mentally exhausted', 'brain fog', 'foggy brain',
  'instant gratification', 'delayed gratification',
  'low motivation', 'no motivation', 'unmotivated', 'lacking drive',
  'paralysis', 'task paralysis', 'analysis paralysis', 'frozen',
  "can't start", 'cant start', 'cannot start', 'hard to start',
  'decision fatigue', 'too many choices', 'indecisive',

  // ── Academic / Work ─────────────────────────────────────────────────────
  'homework takes forever', 'assignments pile up', 'behind on work',
  'falling behind', 'catch up', 'playing catch up',
  'study habits', 'study skills', 'note taking', 'taking notes',
  'reading comprehension', 'lose place reading', 'reread',
  'careless mistakes', 'silly errors', 'sloppy work',
  'underperform', 'underachieve', 'potential',
];

export const autismWords = [
  // ── Clinical / Medical ──────────────────────────────────────────────────
  'autism', 'autistic', 'asd', 'asperger', 'aspergers', 'spectrum',
  'autism spectrum', 'autism spectrum disorder', 'on the spectrum',
  'neurodiverg', 'neurodivers', 'neurodivergent', 'neurodiverse',
  'neurotypical', 'atypical', 'different brain', 'wired differently',
  'high functioning', 'low functioning', 'level 1', 'level 2', 'level 3',
  'pervasive developmental', 'pdd', 'pdd-nos',

  // ── Sensory ─────────────────────────────────────────────────────────────
  'sensory', 'sensory processing', 'sensory integration',
  'overstimulat', 'overstimulated', 'overstimulation',
  'understimulat', 'understimulated', 'understimulation',
  'sensory overload', 'sensory overwhelm', 'sensory meltdown',
  'sensory diet', 'sensory room', 'sensory break',
  'weighted blanket', 'compression vest', 'noise cancelling',
  'stimming', 'stim', 'stims', 'self stimulatory',
  'flapping', 'hand flapping', 'arm flapping',
  'rocking', 'body rocking', 'spinning', 'twirling',
  'loud noise', 'noise', 'noisy', 'sound sensitiv',
  'too loud', 'too noisy', 'hate noise', 'noise hurts',
  'bright light', 'bright lights', 'fluorescent', 'flickering', 'flashing',
  'too bright', 'lights bother', 'lights hurt',
  'texture', 'textures', 'fabric', 'clothing tag', 'tags bother',
  'itchy', 'scratchy', 'rough fabric', 'seams bother',
  'food texture', 'picky eat', 'picky eater', 'food aversion',
  'smell', 'smells bother', 'strong smells', 'taste sensitiv',
  'overwhelm', 'overload', 'overwhelming', 'too much',
  'too much information', 'too fast', 'too loud', 'too bright',
  'crowded', 'crowd', 'crowds', 'too many people', 'busy places',
  'overstimulating', 'chaotic environment',

  // ── Social / Communication ──────────────────────────────────────────────
  'social situation', 'social situations', 'social interaction',
  'social skills', 'social cue', 'social cues', 'social rules',
  'eye contact', 'making eye contact', 'avoid eye contact',
  'facial expression', 'facial expressions', 'reading faces',
  'body language', 'reading body language', 'nonverbal cues',
  'tone of voice', 'sarcasm', 'idiom', 'idioms', 'figure of speech',
  'literal', 'take literally', 'literal thinking', 'literal interpretation',
  'metaphor', 'double meaning', 'implied meaning', 'subtext',
  'small talk', 'conversation', 'conversations', 'chitchat',
  'awkward silences', 'dont know what to say',
  'hard to talk to people', 'dont understand people',
  'people confusing', 'social anxiety', 'social phobia',
  'mask', 'masking', 'pretending', 'pretend to be normal',
  'exhausting to socialize', 'social exhaustion', 'social fatigue',
  'prefer alone', 'need alone time', 'solitude', 'introvert',
  'selective mutism', 'nonverbal', 'non verbal', 'non-verbal', 'mute',
  'echolalia', 'scripting', 'rehearsed speech', 'flat affect', 'monotone',

  // ── Routine / Predictability ────────────────────────────────────────────
  'routine', 'routines', 'schedule', 'schedules', 'structured',
  'predictab', 'predictable', 'predictability', 'need predictability',
  'unpredictab', 'unpredictable', 'hate surprises', 'no surprises',
  'change', 'changes', 'hate change', 'resist change', 'fear of change',
  'transition', 'transitions', 'hard transitions', 'switching activities',
  'unexpected', 'surprise', 'surprises', 'new environment',
  'new situation', 'unfamiliar', 'different routine', 'break in routine',
  'same way', 'same order', 'same route', 'same food',
  'sameness', 'need sameness', 'consistency',
  'repetitive', 'repetition', 'pattern', 'patterns',

  // ── Special Interests ───────────────────────────────────────────────────
  'special interest', 'special interests', 'intense interest',
  'obsess', 'obsession', 'fixat', 'fixation', 'passion', 'passions',
  'deep dive', 'know everything about', 'expert on',
  'infodump', 'info dump', 'talk about it nonstop',

  // ── Meltdown / Shutdown ─────────────────────────────────────────────────
  'meltdown', 'meltdowns', 'shutdown', 'shut down', 'shutting down',
  "can't cope", 'cant cope', 'cannot cope', 'falling apart',
  'losing control', 'out of control', 'breaking down',
  'need quiet', 'need space', 'need alone', 'need break', 'decompress',
  'safe space', 'comfort zone', 'calming', 'soothing', 'self soothe',

  // ── Emotional / Regulation ──────────────────────────────────────────────
  'anxious', 'anxiety', 'nervous', 'worried', 'panic', 'stress',
  'emotional regulat', 'self regulat', 'dysregulat',
  'over think', 'overthink', 'overthinking', 'ruminate', 'ruminat',
  'burnt out', 'burnout', 'autistic burnout', 'exhausted',
  'spoon theory', 'low spoons', 'no spoons', 'energy budget',
  'executive function', 'planning', 'organiz', 'priorit',
  'processing speed', 'processing time', 'need more time',
  'slow processing', 'takes longer to process',
];

export const physicalWords = [
  // ── Clinical / Medical ──────────────────────────────────────────────────
  'physical', 'physical disability', 'physical impairment',
  'motor', 'motor skills', 'motor function', 'motor impairment',
  'fine motor', 'gross motor', 'motor control', 'motor planning',
  'cerebral palsy', 'cp', 'muscular dystrophy', 'md',
  'spinal cord', 'spinal cord injury', 'sci', 'spinal injury', 'spine',
  'back injury', 'back problems', 'herniated disc', 'spinal fusion',
  'quadripleg', 'quadriplegic', 'quadriplegia',
  'parapleg', 'paraplegic', 'paraplegia',
  'hemipleg', 'hemiplegic', 'hemiplegia',
  'tetrapleg', 'tetraplegic', 'tetraplegia',
  'stroke', 'post stroke', 'stroke survivor', 'hemiparesis',
  'brain injury', 'tbi', 'traumatic brain', 'traumatic brain injury',
  'multiple sclerosis', 'ms', 'als', 'amyotrophic lateral sclerosis',
  'parkinsons', 'parkinson', 'essential tremor',
  'arthritis', 'rheumatoid', 'osteoarthritis', 'joint',
  'fibromyalgia', 'chronic pain', 'neuropathy', 'nerve damage',
  'carpal tunnel', 'repetitive strain', 'rsi',
  'ehlers danlos', 'eds', 'hypermobility',

  // ── Mobility ────────────────────────────────────────────────────────────
  'wheelchair', 'wheel chair', 'power chair', 'electric wheelchair',
  'mobility', 'immobile', 'immobility', 'limited mobility',
  'walk', 'walking', 'cant walk', 'cannot walk', 'hard to walk',
  'trouble walking', 'difficulty walking', 'unsteady gait',
  'limp', 'limping', 'shuffling', 'dragging feet',
  'crutch', 'crutches', 'walker', 'rollator', 'walking frame',
  'scooter', 'mobility scooter', 'motorized scooter',
  'standing', 'cant stand', 'cannot stand', 'hard to stand',
  'sitting', 'cant sit', 'cannot sit', 'sitting for long',
  'transfer', 'bed transfer', 'chair transfer',
  'stair', 'stairs', 'steps', 'ramp', 'elevator', 'accessible',
  'fall', 'falling', 'falls', 'balance', 'unbalanced', 'unsteady',
  'coordination', 'poor coordination', 'lack of coordination',

  // ── Upper body / Hands ──────────────────────────────────────────────────
  'limb', 'limbs', 'arm', 'arms', 'leg', 'legs', 'hand', 'hands',
  'finger', 'fingers', 'wrist', 'wrists', 'shoulder', 'elbow',
  'amputee', 'amputation', 'prosthetic', 'prosthesis', 'prosthetics',
  'missing arm', 'missing hand', 'missing leg', 'missing limb',
  'one hand', 'single hand', 'left hand', 'right hand', 'one arm',
  'dexterity', 'grip', 'grasp', 'pinch', 'grip strength',
  'weak grip', 'weak hands', 'hand weakness', 'finger weakness',
  'tremor', 'tremors', 'shaking', 'shaky hands', 'hand tremors',
  'spasm', 'spasms', 'spastic', 'spasticity', 'muscle spasm',
  'stiff', 'stiffness', 'rigid', 'rigidity', 'tight muscles',
  'paralys', 'paralyzed', 'paralysis', 'partial paralysis',
  'movement', 'limited movement', 'restricted movement',
  'range of motion', 'reduced range', 'frozen joint',

  // ── Computer / Input ────────────────────────────────────────────────────
  'typing', 'cant type', 'cannot type', 'hard to type', 'trouble typing',
  'keyboard', 'mouse', 'trackpad', 'touchpad', 'touchscreen',
  'click', 'clicking', 'cant click', 'hard to click', 'trouble clicking',
  'scroll', 'scrolling', 'swipe', 'swiping', 'drag', 'dragging',
  'double click', 'right click', 'hold and drag',
  'assistive device', 'adaptive device', 'adaptive equipment',
  'switch control', 'switch access', 'single switch',
  'eye tracking', 'eye gaze', 'head pointer', 'head mouse',
  'voice control', 'voice command', 'voice input', 'voice typing',
  'dictation', 'speech recognition', 'dragon naturally speaking',
  'sip and puff', 'mouth stick', 'head wand',
  'on screen keyboard', 'virtual keyboard', 'ergonomic keyboard',
  'trackball', 'joystick', 'adaptive mouse', 'foot mouse',

  // ── Pain / Fatigue ──────────────────────────────────────────────────────
  'pain', 'painful', 'hurts', 'aching', 'chronic pain', 'constant pain',
  'fatigue', 'fatigued', 'tired easily', 'exhaustion',
  'energy', 'low energy', 'no energy', 'stamina', 'endurance',
  'flare', 'flare up', 'good days bad days',
  'pacing', 'energy management', 'rest breaks',
  'adaptive', 'accommodation', 'accessibility',
  'accessible', 'barrier free', 'universal design',
  
  // ── Deaf / Hearing Loss ─────────────────────────────────────────────────
  'deaf', 'deafness', 'hearing loss', 'hearing impaired', 'hard of hearing',
  'cannot hear', 'cant hear', 'hard to hear', 'trouble hearing',
  'hearing aid', 'hearing aids', 'cochlear', 'cochlear implant',
  'sign language', 'asl', 'bsl', 'interpreter', 'sign interpreter',
  'captions', 'subtitles', 'closed captions', 'closed captioning',
  'lip reading', 'read lips', 'tinnitus', 'ringing in ears',
  'ear infection', 'ear damage', 'lost hearing', 'born deaf',
  'partially deaf', 'completely deaf', 'profoundly deaf',
  'audio description', 'visual alerts', 'vibrating alerts',
  'need transcript', 'transcript', 'transcription',
  'sound is muffled', 'muffled sound', 'speech is muffled',
  'audiologist', 'audiogram', 'decibels', 'db',
  'sensorineural', 'conductive hearing loss'
];

export const dyslexiaWords = [
  // ── Clinical / Medical ──────────────────────────────────────────────────
  'dyslexia', 'dyslexic', 'dyscalculia', 'dysgraphia', 'dyspraxia',
  'learning disability', 'learning difficulty', 'learning disorder',
  'learning difference', 'specific learning disability', 'sld',
  'processing disorder', 'auditory processing', 'auditory processing disorder',
  'visual processing', 'visual processing disorder',
  'language processing', 'language disorder',
  'phonological awareness', 'phonological processing',
  'orthographic processing', 'rapid naming', 'rapid automatized naming',
  'working memory', 'short term memory', 'long term memory',
  'retain information', 'memory retention', 'recall',

  // ── Reading ─────────────────────────────────────────────────────────────
  'read', 'reading', 'reader', 'slow reader', 'poor reader',
  'reading speed', 'reading fluency', 'reading level',
  'reading comprehension', 'reading difficulty', 'reading problem',
  'reading struggle', 'reading challenge',
  'cant read', 'cannot read', 'hard to read', 'trouble reading',
  'difficulty reading', 'struggling to read', 'hate reading',
  'avoid reading', 'scared of reading', 'reading aloud',
  'lose my place', 'lose place', 'skip lines', 'skip words',
  'reread', 'rereading', 'read again', 'read multiple times',
  'decode', 'decoding', 'decode words', 'sound out',
  'sounding out', 'phonics', 'phonetic', 'phoneme',
  'fluency', 'reading fluency', 'choppy reading', 'halting reading',
  'slow reading', 'laborious reading',
  'sight words', 'word recognition', 'word identification',
  'comprehension', 'understanding text', 'understand what i read',
  'misread', 'misreading', 'reading errors', 'guessing words',

  // ── Letters / Words ─────────────────────────────────────────────────────
  'letter', 'letters', 'word', 'words', 'alphabet',
  'mix up letters', 'confuse letters', 'swap letters', 'transpose letters',
  'letters jump', 'letters move', 'letters swim', 'letters dance',
  'letters flip', 'letters reverse', 'letters backwards',
  'b and d', 'p and q', 'b d confusion', 'p q confusion',
  'mirror', 'mirror writing', 'reverse', 'reversed', 'backward', 'backwards',
  'reading backwards', 'writing backwards', 'letters look wrong',
  'words look wrong', 'words move around', 'words blur',
  'words jump', 'words swim', 'words float', 'dancing words',
  'crowded text', 'text too close', 'letters too close',
  'visual stress', 'irlen syndrome', 'scotopic sensitivity',
  'colored overlays', 'tinted lenses', 'reading ruler',

  // ── Spelling ────────────────────────────────────────────────────────────
  'spell', 'spelling', 'speller', 'poor speller', 'bad speller',
  'cant spell', 'cannot spell', 'hard to spell', 'trouble spelling',
  'bad at spelling', 'spelling mistakes', 'spelling errors',
  'misspell', 'misspelling', 'spell check', 'spell checker',
  'inconsistent spelling', 'random spelling', 'creative spelling',
  'invented spelling', 'phonetic spelling',

  // ── Writing ─────────────────────────────────────────────────────────────
  'writing', 'write', 'writer', 'written', 'handwriting',
  'cant write', 'cannot write', 'hard to write', 'trouble writing',
  'difficulty writing', 'poor handwriting', 'messy handwriting',
  'illegible', 'illegible handwriting', 'pencil grip', 'pen grip',
  'forming letters', 'letter formation', 'print vs cursive',
  'slow writer', 'takes long to write', 'writing speed',
  'written expression', 'express in writing', 'organize thoughts',
  'paragraph structure', 'essay writing', 'composition',
  'grammar', 'punctuation', 'capitalization', 'sentence structure',
  'copying from board', 'copying text', 'transcription',
  'note taking', 'taking notes', 'class notes',

  // ── Numbers / Math (Dyscalculia) ────────────────────────────────────────
  'math', 'maths', 'mathematics', 'arithmetic', 'calculation',
  'numbers', 'number', 'counting', 'number sense',
  'number reversal', 'number confusion', 'math facts',
  'times tables', 'multiplication', 'division',
  'place value', 'decimal', 'fraction', 'fractions',
  'word problems', 'math word problems', 'story problems',
  'mental math', 'mental arithmetic', 'head math',
  'math anxiety', 'scared of math', 'hate math',
  'clock reading', 'telling time', 'analog clock',
  'money', 'counting money', 'making change',
  'measurement', 'measuring', 'estimation',

  // ── Academic / School ───────────────────────────────────────────────────
  'slow learner', 'learn slowly', 'takes longer', 'need extra time',
  'extended time', 'extra time', 'accommodations',
  'tutoring', 'tutor', 'remedial', 'remediation',
  'special education', 'special ed', 'sped', 'iep',
  'individualized education', '504 plan', '504',
  'resource room', 'learning support', 'intervention',
  'study', 'studying', 'study skills', 'study strategies',
  'homework', 'assignment', 'assignments', 'exam', 'test', 'tests',
  'grade', 'grades', 'failing', 'behind', 'catch up', 'gap',
  'academic struggle', 'school struggle', 'falling behind',
  'repeating grade', 'held back', 'retained',
  'literacy', 'literate', 'illiterate', 'functional literacy',
  'text to speech', 'audiobook', 'audiobooks', 'audio version',
  'assistive technology', 'reading software', 'writing software',
  'speech to text', 'dictation', 'voice typing',
];

export const allSymptomsMapping = {
  visual: visualWords,
  adhd: adhdWords,
  autism: autismWords,
  physical: physicalWords,
  learning: dyslexiaWords
};
